[build]
  command = "npm install --include=dev --prefix decisa-backend && npm install --include=dev --prefix decisa-frontend && cd decisa-backend && npx prisma generate && cd ../decisa-frontend && npm run build"
  publish = "decisa-frontend/dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["express"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200